### PR TITLE
Update to acc.js

### PR DESCRIPTION
**Pull request by DevJhozi**
Refactored your code

Using the DRY principle, I used a Ternary Operator for a block on your code where you used if else statement.

### CODE REVIEW

**Comment by SholaCity** [comment]
Excellent eye Jhozi but this repository and other uncompleted or recreated repos will be deleted soon. 

I already created a newer version of this website (original novaltech) and you can check it out.

I'll some more projects and it'll be nice have you around.

Your request with will be accepted

**Comment by SholaCity** [comment]
Excellent eye but

**Comment by SholaCity** [comment]
You forgot to spell the height correctly

**Comment by DevJhozi** [comment]
Alright

**Pull request merged**
